spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:workforce
    driver-class-name: org.h2.Driver
    username: sa

  jpa:
    hibernate:
      ddl-auto: create-drop
    database: h2

logging:
  level:
    org:
      springframework:
        web: debug
      hibernate:
        SQL: debug
